# Path to the raw CSV export downloaded from Google Drive.
# Provide an absolute path or a path relative to the project root.
raw_data: "data/raw/AI Help (Udhyam) student usage_Table - Sheet1.csv"

# Disable if you do not want to call the OpenAI API via scripts/02_translate_messages.py.
enable_openai_translation: false
